name: Build

on: [push]

jobs:
  build:
    if: github.actor == 'premist'
    runs-on: [self-hosted, macOS-arm64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build
        shell: /bin/zsh {0}
        working-directory: src/ruby
        run: |
          source $HOME/.zshrc
          chruby ruby-2.7.2

          arch -arm64 bundle config set --local force_ruby_platform true
          arch -arm64 bundle

          arch -arm64 rake
